run_qemu.sh

Use zstd to uncompress file with .zst extension, then call tar
command to untar it.
Signed-off-by: Jonathan Zhang <jonzhang@fb.com>

run_qemu.sh: fix the issue related to uncompressing of ZST file

---

run_qemu.sh

The check to install vimrc type files used a glob which fails if one has
more than one .vim* type file.
Use .vimrc to trigger copying a vim environment.
Signed-off-by: Ira Weiny <ira.weiny@intel.com>

run_qemu: Don't use glob in if statement

---

mkosi.ubuntu.default.tmpl

The following packages were added:
* fio: flexible I/O tester
* lsof: Utility to list open files
* ltrace: Track runtime library calls
* ndctl: the packages tht provides the cxl CLI in Ubuntu
* openssh-client: SSH client, was missing
* strace: System call tracer
Signed-off-by: Jonathan Gonzalez V <jonathan.abdiel@gmail.com>

mkosi.ubuntu: Add some missing packages

---

mkosi.ubuntu.default.tmpl
run_qemu.sh

Dear Maintainers,
I am using run_qemu in a limited way, build outside the kernel source directory and create vanilla images without needing qemu to set up a special platform to run it in. While run_qemu could do much more it would be great if it could support this minimal workflow also. The changes in this pull request supports this workflow. 
Thank you
Reinette

Changes in support of minimal workflow

---

parser_generator.m4
run_qemu.sh

Testing of core kernel functionality is often implemented in the kernel selftests located in source sub-tree tools/testing/selftests.
Running these tests are often required to properly ensure kernel changes have not created a regression.
Add --kern-selftests option to include a build of the kernel selftests in the root home dir of the qemu build.  Due to the lengthy build time the default for this option is 'off'.
Signed-off-by: Ira Weiny <ira.weiny@intel.com>

run_qemu: Add kernel selftests build option

---

mkosi.arch.default.tmpl

If ~/git/ndctl exists, it will build the ndctl by default.  But in Archlinux, it will get error because the required packages are missing. So, add them here.

mkosi.arch: add requirement packages for ndctl

---

README.md
parser_generator.m4
run_qemu.sh

Some tests benefit from getting dax module debug messages.  Specifically Dynamic Capacity Devices require the use of dax devices to fully test the management of extents.
Add an option --dax-debug to add the debug messages for some dax modules including dax_cxl.

run_qemu: Add dax debug switch

---

mkosi.arch.default.tmpl
mkosi.fedora.default.tmpl
mkosi.ubuntu.default.tmpl
run_qemu.sh

In some cases, such as fedora37, 'insufficient disk space error' was occurred during building the root.img.
The root cause is that the ESPSize(256M by default) is not set in the mkosi.fedora.default.tmpl.  If the ESP partition is larger than 256M, this error(shown as below) occurrs.
So, extend the ESPSize to 512M for all distroes to avoid the error.
Error log:
$ run_qemu.sh --cxl
...
‣  Refreshed partition table.
‣  Attaching /home/linux-6.7/qbuild/.mkosi-ru0kjlr1 as loopback… ‣  Attached /dev/loop0
‣  Refreshing file system /dev/loop0p2…
tune2fs 1.46.5 (30-Dec-2021)
‣  Mounting image…
‣  Copying in extra file trees…
‣  Generating initramfs images…
/usr/bin/dracut: line 1056: /sys/module/firmware_class/parameters/path: No such file or directory dracut: No '/dev/log' or 'logger' included …

run_qemu: extend the size of ESP partition

---

run_qemu.sh

Argbash cannot report if an invalid parameter is set, it will think this parameter as working_dir, and then show meaningless message:
$ run_qemu.sh --clx
/usr/local/bin/run_qemu.sh: line 105: pushd: --clx: invalid number
pushd: usage: pushd [-n] [+N | -N | dir]
couldn't cd to --clx
Add check and print useful message:
$ run_qemu.sh --clx
Invalid option '--clx'
Try 'run_qemu.sh --help' for more information.

run_qemu.sh: Prompt invalid parameter error

---

run_qemu

The 'kernel' argument is deprecated, and 'imgcache' is newly added for the --rebuild, but we can still find the 'kernel' through bash completion and can not find 'imgcache':
$ run_qemu.sh --rebuild=
img     kernel  kmod    none    wipe

run_qemu: update the arguments of --rebuild in completion script

---

run_qemu.sh

The latest upstream qemu master requires memory backend files to be a multiple of 4k.
Change the label size to be 4k to match this requirement.

run_qemu: Label size must be 4K

---

run_qemu.sh

The label size of 4k may not hold a modern Optane label.  While the 4k value fixed the issue with qemu a more reasonable value is 128k which can safely hold many labels.
Increase the label space to 128k

run_qemu: Increase label size to a more usable value

---

run_qemu.sh

Use host CPU capability to avoid guest boot failed issue: Fatal glibc error: CPU does not support x86-64-v2

run_qemu.sh: use host CPU capability to avoid guest boot failed issue

---

run_qemu.sh

Add more cmdline for testing and debug:
1. add initcall_debug to debug some module init hang issues easily
2. add log_buf_len=20M for dmesg log size, when test cxl qemu ndctl cases, could not collect the full dmesg log due to default dmesg size is too small, now set dmesg size to 20M as default, it's enough for dmesg debug.

run_qemu.sh: add more cmdline for testing and debug

---

run_qemu.sh

Stop failing and aborting the entire build when .ssh/id_rsa.pub is not found; RSA is outdated and insecure. Instead, install all .pub keys for which we have the private part. As a bonus, this also keeps building on systems that have no private keys (e.g. when using ssh agent forwarding).

run_qemu.sh: de-hardcode .ssh/id_rsa.pub

---

run_qemu.sh

Warning: this is VERY FAR from enough to make run_qemu.sh compatible with recent mkosi versions. But it helps.

Minor fixes to run mkosi from git

---

mkosi.arch.default.tmpl
mkosi.debian.default.tmpl
mkosi.fedora.default.tmpl
mkosi.generic.conf.tmpl
mkosi.ubuntu.default.tmpl
run_qemu.sh

Again this is still a bit far from achieving compatibility with mkosi v15 but this time it's a major step forward - and this should have zero effect on v14 users for now.
See commit messages.

mkosi.conf fixes to prepare for v15. Bump required version to v11

---

mkosi.generic.conf.tmpl

mkosi.generic.conf.tmpl: re-enable UnifiedKernelImages
This reverts commit 92ac46548ca7d933383ec8617311052bf6a3d12a
The build of the Unified Kernel Image was disabled 18 months ago but no one can remember now what problem this solved at the time. It should be possible to just ignore this byproduct.
For some unknown reason, reverting this fixes the build on Ubuntu 22.04 with mkosi version 12:
```
running: sudo -E mkosi -i -f --autologin build
Error: Sorry, --without-unified-kernel-images is not supported in
UEFI mode on this distro.
```
Reverting this also helps the (upcoming) compatibility with mkosi v15+ because this option has been entirely removed from mkosi v15+! Quoting any recent mkosi/NEWS.md:
```
v15
We also remove the WithoutUnifiedKernelImages= switch as building
unified kernel …
```

Revert "run_qemu: switch mkosi to not build unified kernel images"

---

mkosi.arch.default.tmpl

Fixes the following error when trying to build with mkosi v15:
>  Setting up autologin…
>  A bootable image was requested but systemd-boot was not found
>     at usr/lib/systemd/boot/efi
I don't know how mkosi v14 does not need this but asking explicitly for systemd does not hurt mkosi v14.

mkosi.arch.default.tmpl: add systemd

---

run_qemu.sh

prepare_qcmd() does not need OVMF binaries, they're needed only later when actually trying to start QEMU. This makes it possible to build successfully with `run_qemu.sh --no-run` even when OVMF binaries are not found (each distro tends to place them in a different place).

run_qemu.sh: move get_ovmf_binaries() later, to start_qemu()

---

run_qemu.sh

2 commits. Main one:
The -P scan is performed in the background. This can be observed with
this simple sequence:
```
losetup -P...
ls -l /dev/disk/by-loop-ref/ # => not found
sleep 1
ls -l /dev/disk/by-loop-ref/ # => found

run_qemu.sh: add a "sleep 2" after (background) losetup -P

---

run_qemu.sh

The update_existing_rootfs() function is part of a hidden shortcut that does not run mkosi. It had a tentative feature that wanted to invoke rsync to update `ndctl` sources in the existing image. That ndctl shortcut never actually did anything!
- Replace that broken rsync with a warning in case anyone thought this was working.
- Do not print the warning when `$ndctl` is undefined or ill-defined because --ndctl-build is ON by default and `$ndctl` is in practice used as the actual ndctl "switch".
1. This feature apparently _never worked_ and always left outdated sources _silently_. That's because the mount point requires root access, which made the `test [ -d qbuild/mnt/root/ndctl ]` always return false - without any message!
2. Even if that `rsync` had worked (with the appropriate …

run_qemu.sh: print warning that --ndctl-build never worked incrementally

---

.github/workflows/main.yml

run_qemu.sh already uses sudo a lot internally, no need to add yet another layer.
Fixes commit 72b51500f5d6 (".github/workflows: add first, new main.yml building on Ubuntu 24")

.github: drop "sudo" in "sudo run_qemu.sh"

---

.github/workflows/main.yml
mkosi.ubuntu.default.tmpl
mkosi/extra/root/ndctl/reinstall.sh
run_qemu.sh

6 commits. Some finer-grained testing in #78

run_qemu.sh: make ndctl compilation compatible with mkosi v15+ 

---

.github/workflows/main.yml

Out of the 11-12 minutes the build currently takes, the kernel compilation uses the vast majority of that time. This is pointless: try to cache that.

.github: add ccache

---

.github/workflows/main.yml

As documented at:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#example-using-multiple-restore-keys
Also add warning about branch restrictions

.github: add .ccache fallbacks using restore-keys:

---

mkosi_tmpl_portable/distro.tmpl
run_qemu.sh

Using one distro to build another one is fraught with peril and most people just want to stick to the same OS. That's how mkosi behaves by default so let's align with that. It's annoying and time-consuming not to forget to tell run_qemu.sh what distribution it is currently running on.  That information is available in /etc/os-release so let's just read it and use it.
To simplify the run_qemu.sh behavior, do not set Distribution=$distro and Release=$rev in mkosi configuration if the user did not provide them. Let mkosi perform its unmodified magic.
Bonus feature: regularly bumping 40 to 41, 42, etc. is not required any more.

run_qemu.sh: default to the build OS like mkosi does instead of Fedora 40

---

run_qemu.sh

This gets the total number of shellcheck warnings down from 22 to just 10.
Also: add a minor depmod comment. Use : instead of # so it shows when using --debug / set -x.

run_qemu.sh: add some missing quotes

---

run_qemu.sh

3 commits.
Main one: Stops creating bogus vmlinuz- and System.map- files.
Bug fix related to #88. Does NOT address the complex 88 issue but removes some confusion from it.

run_qemu.sh: update_existing_rootfs: pass -x to make_install_kernel

---

run_qemu.sh

remove sleep 5 after 'sync' in umount_rootfs()
'sync' means 'sync': it is blocking so there's no need for a random delay.
Fixes commit ee43cb8a9d1b ("run_qemu: fix occasional umount failures") which added both at the same time.

run_qemu.sh: remove 'sleep 5' after 'sync'

---

run_qemu.sh

run_qemu.sh: do not look for unused OVMF binaries on --legacy-bios

---

run_qemu.sh

Minor fixes that help clarify the #88 situation a bit.

EFI System Partition cleanups

---

run_qemu.sh

The purpose of the --filesystems= parameter is a bit counter-intuitive: it's designed to _reduce_ the size of the initrd by excluding all modules except the ones given.
```
man dracut
--filesystems <list of filesystems>
Specify a space-separated list of kernel filesystem modules
to EXCLUSIVELY include in the generic initramfs.
```
Emphasis mine.
So, the previous "xfs ext4" argument could prevent someone with another filesystem module to boot.
Worse: if CONFIG_XFS_FS is false, then passing "xfs ext4" prints the following warning:
```
dracut-install: Failed to find module 'xfs'
dracut[E]: FAILED:  /usr/lib/dracut/dracut-install -D
/var/tmp/dracut.eRkJZX/initramfs -N ^nfit$|^libnvdimm$|^nd_pmem$
--kerneldir ./qbuild/mkosi.extra/lib/modules/6.12.0-dirty -m xfs ext4
```
Then, dracut does not …

run_qemu.sh: drop dracut --filesystems="xfs ext4" parameter

---

mkosi.arch.default.tmpl
mkosi.ubuntu.default.tmpl

Very useful to move files between host and guest.
No reason only for Fedora to have it.

mkosi: add "rsync" to Arch and Ubuntu

---

run_qemu.sh

Critical fix for mkosi versions v25 and above that include massive change commit b3a3e7e7fcb2 ("Introduce mkosi-sandbox and stop using subuids for image builds")
Fixes the following failure:
```
Running postinstall script kernel/qbuild/mkosi.postinst
Traceback (most recent call last):
File "mkosi/mkosi/sandbox.py", line 924, in <module>
File "mkosi/mkosi/sandbox.py", line 913, in main
File "<frozen os>", line 609, in execvp
File "<frozen os>", line 632, in _execvpe
OSError: [Errno 8] Exec format error
"/work/postinst final" returned non-zero exit code 1.
```
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

run_qemu.sh: add !#/bin/sh shebang for mkosi.postinst

---

parser_generator.m4
run_qemu.sh

QEMU devices are not required to run cxl tests, so let the user decide what they want.
Autorun has very recently been fixed (commit 17d0473a629a and others in PR #101) and had been broken for likely 1 or 2 years which means no one was using it which means it's a great time to alter the behavior.

run_qemu.sh: stop --cxl-test-run from forcing --cxl QEMU devices

---

.github/workflows/cxl-test.cfg
.github/workflows/main.yml

Now making sure that --cxl-test builds tests from ndctl.
New .github/workflows/cxl-test.cfg based on ndctl.git/README.md.
Still --no-run cause running in a Github runner VM.
Also drop --cxl which was a misunderstanding: this merely configures QEMU which is not used here.

.github: new cxl-test.cfg from ndctl/README.md; add --cxl-test

---

.github/workflows/main.yml

Also explains when and how it fails.
It does not work but it's ready to be used on a different runner and it also indirectly serves as documentation.

.github: install qemu-system-x86

---

run_qemu.sh

Until mkosi v24 commit c236c9f7b9c82d3, `mkosi --autologin` used to be applied to four devices: console, tty1, ttyS0 and one architecture-dependent device.
mkosi has some QEMU features of its own to boot the image. run_qemu.sh never used any of that. We should probably try (some of) it in the future but I digress. In that mkosi commit, `mkosi/qemu.py` (which we don't use) stopped using `ttyS0` and replaced it with the faster `/dev/hvc0` instead. The image building code (which we DO use!) was updated correspondingly without caring about backwards compatibility and dropped ttyS0 on the floor. Someone noted this in
https://github.com/systemd/mkosi/pull/2834 and the recommendation was to switch to systemd credentials: exactly what this commit does. The mkosi maintainer also expressed the …

run_qemu.sh: drop mkosi --autologin, use systemd credentials instead

---

.github/workflows/main.yml
contrib/tmpfs_workspace.tmpl
run_qemu.sh

I've been selfishly enjoying this major optimization for a while; time to share it. Very small hence very easy to comment out or even revert if needed.
mkosi-workspace is located on /var/tmp/ by default, which is usually persistent and slow storage which wears out.  On success, mkosi-workspace is deleted at the end of the build so it really does not need to be located on persistent storage. So, move it to /tmp which is usually tmpfs.
On one of my systems, moving to tmpfs lowers the build time from 4 min to 1 min! If you ever wondered how I could git bisect mkosi faster than reading its release notes: that's how.

Show how to move mkosi WorkspaceDirectory to /tmp(fs)

---

mkosi.arch.default.tmpl

Also add `python-prefixed` that can pretty-print large addresses.

mkosi.arch.default.tmpl: add python-pip

---

mkosi.arch.default.tmpl

I think we can agree that `lspci` is somewhat useful for CXL.

mkosi.arch.default.tmpl: add pciutils

---

mkosi/extra/root/reinstall_ndctl.sh
run_qemu.sh

Copy everything found in mkosi/extra/ to the image

---

mkosi.arch.default.tmpl
mkosi.fedora.default.tmpl
mkosi.ubuntu.default.tmpl

This allows the guest to mount any host directory "out of the box" with zero qemu or kernel feature to enable.  Thanks to `dpipe` and "reverse sshfs", this does not require any additional ssh configuration either:
https://blog.dhampir.no/content/reverse-sshfs-mounts-fs-push
```
dpipe /usr/lib/openssh/sftp-server = ssh CLIENT sshfs :/mnt/host/path /mnt/client/path -o slave
```
This Just Works out of the box.
Just for the record, virtiofs and 9P are the most popular and likely much faster alternatives but sshfs is "good enough" in most cases. virtiofs seems to clash with what we already do ("NUMA distance missing" error, etc.) and 9P is rumoured to be quite slow too.
Also add "ping" and friends on Arch Linux.

Packages: add sshfs

---

mkosi/extra/root/reinstall_ndctl.sh

The added flexibilty is useful when using sshfs

reinstall_ndctl.sh: add optional ndctl_src parameter

---

run_qemu.sh

This gets the total number down to 5 warnings.
Don't forget to use -x:
shellcheck -x run_qemu.sh

Shellcheck fixes

---

run_qemu.sh

2 commits. Main one:
Fixes commit https://github.com/pmem/run_qemu/commit/ff1ece56dbca7feeaa624578762b0b2c31f80026 ("run_qemu.sh: use host CPU capability to
avoid guest boot failed issue")
"-cpu host" requires KVM.
Hyperthreading requires recent CPUs.

run_qemu.sh: fix --no-kvm option

---

mkosi.arch.default.tmpl

This provides... the /sbin/init symbolic link which is required to boot with --no-direct-kernel!

mkosi.arch.default.tmpl: add systemd-sysvcompat to fix --no-direct-kernel

---

mkosi.arch.default.tmpl
parser_generator.m4

Instead of describing what we expect from QEMU, only describe what we do.

run_qemu.sh: clarify --legacy-bios help string

---

mkosi.ubuntu.default.tmpl

I've tested the package builtd properly and lspci worked in the aarch64 VM. Please pull.

Add pciutils package to the Ubuntu list

---

run_qemu.sh

After actually understanding --legacy-bios (8ead07f00639), it's much easier than I thought.

run_qemu.sh: do not look for Shell.efi when using --legacy-bios

---

.github/workflows/main.yml
arch_vars.sh
debian_vars.sh
fedora_vars.sh
run_qemu.sh
ubuntu_vars.sh

This was a horrible, unreliable and non-portable hack.

Complete rewrite of get_ovmf_binaries()

---

mkosi_tmpl_from_v15/ubuntu-ESP.tmpl

Rather than constantly growing the list of releases that need systemd-boot, list the only we support that does not have it.

ubuntu-ESP.tmpl: switch to a Release=! negation for 25.04

---

run_qemu.sh

run_qemu.sh: replace "sleep 1+2" with polling in mount_rootfs()

---

.github/workflows/main.yml

Required for new scheduled.yml to invoke it.
As reported in https://github.com/pmem/run_qemu/actions/runs/14606426775
Invalid workflow file: .github/workflows/scheduled.yml#L23 error parsing called workflow
".github/workflows/scheduled.yml"
-> "./.github/workflows/main.yml" (source branch with sha:b80bd6904c...) : workflow is not reusable as it is missing a `on.workflow_call` trigger

.github: main.yml: add on.workflow_call

---

run_qemu.sh

Fixes #137. Hardcoding also reported in #140
Leverages old code already used by /efi and --no-direct-kernel.
This commit affects only --direct-kernel

run_qemu.sh: un-hardcode /dev/sda2 in QEMU parameters

---

.github/workflows/main.yml

Now that building from scratch works, let's be more demanding.

.github: add new step "incremental build"

---

run_qemu.sh

Instead of editing in place, comment out and append. This preserves "history", especially when building in incremental mode.
This is the "zero functional change" part of the QEMU / KVM / breakpoint PR #135 for issue #11

run_qemu.sh: refactor loader.conf logic to disable and append

---

.github/workflows/main.yml

Upload test logs when they are the most useful.
Signed-off-by: Marc Herbert <marc.herbert@intel.com>
@marc-hb

.github: upload test logs on failure

---

scripts/rq_cxl_tests.sh

Fixes shellcheck warning just introduced.

rq_cxl_tests.sh: quote new $NDCTL expansion

---

scripts/rq_cxl_tests.sh

Fix dumpfile() to split lines longer than 1024 lines. They were silently dropped; the "invalid write" message was generally lost in the various redirections.
Also define IFS= to stop trimming whitespace and use the filename as a message prefix.

rq_cxl_tests.sh: stop losing lines longer than 1024 bytes

---

.github/workflows/cxl-test.cfg

Trim down the nvdimm section copied from ndctl.git/README.md, remove requirements not required by the CXL test suite.

.github/workflows/cxl-test.cfg: remove NVDIMM requirements not needed

---

scripts/rq_cxl_tests.sh

Set the kernel default_message_loglevel to NOTICE to make sure rq_cxl_tests.sh > /dev/kmsg does not pollute test results.

rq_cxl_tests.sh: set kernel default_message_loglevel to NOTICE

---

mkosi.arch.default.tmpl
mkosi.fedora.default.tmpl
mkosi.ubuntu.default.tmpl

Needed by some ndctl/dax tests.
Fixes: 2e450c06e (run_qemu: add asciidoc and trace-cmd to the fedora template)

ubuntu/arch: add trace-cmd, xxd and parted packages

---

.github/workflows/nfit-test.cfg

This is enough to pass the ndctl:ndctl and ndctl:dax test suites.

.github: add new nfit-test.cfg

---

scripts/rq_nfit_results.sh

This is a pure copy of commit 40878b6bbb5c and the small bit required from 40878b6bbb5c~1
Massive de-duplication is required but that's for another day.

rq_nfit_results.sh: fix compatibility with meson 1.8

---

mkosi.debian.default.tmpl

mkosi versions v15 and above need a lot more explicit Packages= like "?priority(important)" and "task ssh-server".  mkosi v15 changed everything, see https://github.com/systemd/mkosi/issues/1971
Missing packages caused a lot of issues like #168, #171, #199 and maybe others.

mkosi.debian.default.tmpl: overdue compatibility with v15

---

run_qemu.sh

Wrap main around a new compound statement { } to force bash to read it entirely before running it. This allows modifying the script while it's running.
Credits to Simon Tatham
https://hachyderm.io/@simontatham/114511220670677410

run_qemu.sh: use the { main; exit "$?"; } trick to allow modifications

---

run_qemu.sh

According to Itaru Kitayama in https://github.com/pmem/run_qemu/pull/210, this fixes the following error:
```
qemu-system-aarch64: -drive file=root.img,format=raw,media=disk: PCI:
Only PCI/PCIe bridges can be plugged into pxb-cxl
```
> Jonathan explains this is due to on arm64 -drive is virtoi-blk by
> default and we need to set a bus via the -device option. Do it as
> Jonathan suggested in:
>
> https://lore.kernel.org/linux-cxl/20250520183109.00002730@huawei.com/
From https://www.qemu.org/docs/master/system/qemu-manpage.html#hxtool-1
The QEMU block device handling options have a long history and have gone
through several iterations as the feature set and complexity of the
block layer have grown. Many online guides to QEMU often reference older
and deprecated options, which can lead to …

run_qemu.sh: replace -drive rootfs with -blockdev + -device
