debian_rootfs.sh, debian_vars.sh, mkosi.debian.default.tmpl, run_qemu.sh, scripts/cxl_bat.sh
Enable Debian distro on the project.
Some minor changes were made to integrate Debian distro.
Added a way to add/modify configure settings without modifying the run_qemu.sh script.
=> Add support to Debian distro

mkosi.debian.default.tmpl, parser_generator.m4, run_qemu.sh
These are some improvements to run_qemu.sh
=> Some improvements

README.md
=> README.md: update Fedora 39+ notes for Fedora 41 (mkosi14 loss) 

.github/CODEOWNERS
=> Add new .github/CODEOWNERS for automated reviewer assignment

README.md
=> README.md: minor, ssh-related fixes

.github/workflows/main.yml
run_qemu.sh needs qemu-img even when --no-run
=> .github: apt install qemu-utils

run_qemu.sh
This is all incredibly subtle, try to dumb it down.
Also: guard against exit code pollution from cleanup()
=> run_qemu.sh: clarify exit status in EXIT trap handler

.github/workflows/main.yml, Patches/ubuntu/24.04/mkosi/0001-Update-libtss2-mu-to-use-apt-search-pattern.patch, Patches/ubuntu/24.04/mkosi/0001-Use-a-subdirectory-of-the-workspace-as-TMPDIR.patch, mkosi_tmpl_from_v15/main.tmpl, mkosi_tmpl_from_v15/password.tmpl, mkosi_tmpl_from_v15/ubuntu-ESP.tmpl, mkosi_tmpl_portable/distro.tmpl, mkosi_tmpl_upto_v14/main.tmpl, mkosi_tmpl_upto_v14/password.tmpl, run_qemu.sh
=> Compatibility with mkosi v15+

run_qemu.sh
=> show unexpected loopbacks when get_loopdev() fails

run_qemu.sh
Propagate -x all the way when using --debug.
=> run_qemu.sh --debug: add -x for setup_*() in update_existing_rootfs()

mkosi.arch.default.tmpl
Add some basic, survival tools.
=> arch: add pacman, hostname, ps, vi, diff and tree

run_qemu.sh
This supports a lack of /etc/localtime (bit me) and should work across distros.
=> run_qemu.sh: use mkosi --timezone $(timedatectl) when mkosi v15+

.github/workflows/main.yml
build kernel ahead of time to see how long it takes.
=> .github: build kernel ahead of time to see how long it takes

mkosi_tmpl_from_v15/main.tmpl, mkosi_tmpl_portable/output.tmpl, mkosi_tmpl_upto_v14/main.tmpl
=> run_qemu.sh: move "Output=@ROOT_FS@" to common, portable directory

run_qemu.sh
See detailed commit messages and previous discussion in abandoned #127
=> run_qemu.sh: always log the QEMU command line

contrib/tmpfs_workspace.tmpl, mkosi_tmpl_portable/distro.tmpl
=> mkosi tips

run_qemu.sh
Cause it is. Also add a header.
No functional change.
=> run_qemu.sh: make conffile= local

run_qemu.sh
Progress towards supporting ARM64 as discussed in #140, #143 and others.
=> Add initial support for arm64 "virt". Default to host architecture

run_qemu.sh
Also fix minor typos in latest commit 193cd6ad7e0a ("Complete rewrite of get_ovmf_binaries()")
=> run_qemu.sh: mention $edk2_vmf_path in error message

run_qemu.sh
Fixes very first commit 95cb2234ec55 ("run_qemu: import the run_qemu.sh script")
=> run_qemu.sh: make debugcon x86-specific and not EDK2-specific

run_qemu.sh
Signed-off-by: Mac Herbert \<marc.herbert@intel.com\>
Tested-by: Itaru Kitayama \<itaru.kitayama@fujitsu.com\>
=> Append highmem, compact-highmem, highmem-ecam, and highmem-mmio to the machine_args var for the virt VM 

run_qemu.sh
extract new function loop2_partuuid() from update_rootfs_boot_kernel() which creates or update the .conf file in the ESP partition.
The goal is to re-use it de-hardcoded /dev/sda2 in the QEMU parameters.
=> run_qemu.sh: extract new function get_partuuid()

.github/workflows/main.yml, .github/workflows/scheduled.yml
=> .github: new scheduled.yml to seed the cache

run_qemu.sh
Remove some duplication. No change.
=> run_qemu.sh: new function rootfs_loop_devs() to de-duplicate

run_qemu.sh
3 commits, see commit messages
=> run_qemu.sh: print a backtrace on failure

scripts/rq_cxl_results.sh
2 logically independent fixes but the second one leverages the first one.
=> rq_results: compatibility with meson 1.8+; show results summary on failure

.github/workflows/cxl-test.cfg
This is required by --cxl-debug which is part of --cxl-test-run
=> .github: CONFIG_DYNAMIC_DEBUG=y
